services:
  postgres:
   image: postgres:15
   container_name: container_postgres_db
   restart:  unless-stopped
   environment:
     POSTGRES_USER: userTarefas
     POSTGRES_PASSWORD: 123456
     POSTGRES_DB: db_tarefas
   ports:
     - "5432:5432"
   volumes:
     - dbdata:/var/lib/postgresql/data
     - ./scripts:/docker-entrypoint-initdb.d
   networks:
     - appnet  
  tarefas-web-api:
    build: 
     context: . 
     dockerfile: src/backend/ListaTarefas.API/Dockerfile
    container_name: tarefas-api
    depends_on:
      - postgres
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=db_tarefas;Username=userTarefas;Password=123456
    networks:
      - appnet

  tarefas-frontend:
    build:
      context: ./src/frontend/tarefas-react
      dockerfile: Dockerfile
    container_name: tarefas-frontend
    depends_on:
      - tarefas-web-api
    networks:
      - appnet


  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tarefas-web-api
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:


    